<?php include("core/header.phtml") ?>
<?php include("navbar/navbar.phtml") ?>
<div class="content">
<div class="page-title"><?= isset($RENDER_VARS["name"]) ? $RENDER_VARS["name"] : "" ?> Account Edit</div>

<form class="boff-bakery-form" action="?page=user&action=edit&uid=<?= $RENDER_VARS["uid"] ?>" method="POST">
    <?php require("forms/csrf.phtml") ?>
    <?php require("forms/put.phtml") ?>

    <div class="form-section">
        <label class="form-label" for="email">New Email</label>
        <input type="text" name="email" class="form-input" id="email-field" autofocus value="<?= isset($RENDER_VARS["old-email"]) ? $RENDER_VARS["old-email"] : "" ?>">
    </div>

    <div class="form-section">
        <label class="form-label" for="password">New Password</label>
        <input type="password" name="password" class="form-input primary-password" id="password-field" data-required="false">
    </div>

    <div class="form-section">
        <label class="form-label" for="password2">Verify New Password</label>
        <input type="password" name="password2" class="form-input secondary-password" id="password2-field" data-required="false">
    </div>

    
    <div class="user-button-group">
        <div class="main-button-group">
            <button type="submit" class="recipe-button primary-button">Save</button>
            <button type="submit" class="recipe-button secondary-button" id="cancel-button">Cancel</button>
        </div>
    </div>
</form>


</div>
<?php include("core/footer.phtml") ?>