<div class="footer-info-container">

    <div class="footer-author-section">
        <a class="footer-link" target="_blank" href="https://github.com/mwaboff/boff-bakery-recipes">
            View the code on Github
        </a>
        ·
        <a class="footer-link" target="_blank" href="https://www.wilmu.edu/technology/information-systems-technologies.aspx">
            Written for Wilmington University's MS-IST (Web Design) Program
        </a>
        ·
        <div class="footer-copyright">© 2020 Michael Aboff</div>

    </div>


</div>